### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by awalterschulze** [goccmack/gocc#125]
In my merging efforts, I seem to have broken the build https://github.com/goccmack/gocc/runs/2164943724

@kfsone would you mind taking a look?

**Comment by kfsone** [comment]
^- should fix.

**Comment by kfsone** [comment]
@awalterschulze I think you merged the fix, can this be closed?

**Comment by awalterschulze** [comment]
Good catch yes :)

**Comment by awalterschulze** [comment]
Thanks again for fixing this :)
