### ISSUE TITLE
How best to parse this?

### ISSUE THREAD

**Issue by suntong** [goccmack/gocc#131]
Is it possible to parse this as-is?

```
<expr> ::= <term> "+" <expr>
        |  <term>

<term> ::= <factor> "*" <term>
        |  <factor>

<factor> ::= "(" <expr> ")"
          |  <const>

<const> ::= integer
```

I'm not asking people to write a BNF parser for me but the question is on the `\n`. I.e., if I put it into

`!whitespace : ' ' | '\t' | '\n' | '\r' ;` 

then how can I reliably tell that one rule is finished and time to start a new one?

What are the best approaches to parse this? thx!

**Comment by suntong** [comment]
well, found that problem still holds.

**Comment by awalterschulze** [comment]
The BNF was written for a single `expr`

If you want multiple, then you need to add another rule, something like:

```
<exprs> ::= <expr> ";" <exprs>
                  |  <expr>
```

You can also probably use newline instead of `;` if you remove the `\n` from whitespace.

**Comment by suntong** [comment]
Ok, thanks for helping!
