### ISSUE TITLE
Streaming Lexer

### ISSUE THREAD

**Issue by gprossliner** [goccmack/gocc#133]
Hi guys!

I'm about to check some implementations for a scanner in go. Because I need to process log files, I can't feed the data at once.
I would need a streaming implementation, eventually based on channels. 

```go
tokens := make(chan Token)  # consumer
l := lexer.NewLexer()
l.Output(tokens); # 

# new data ([]byte) is feed into scanner, maybe emitting new tokens to Output channel
l.Input <- data  
```

Do you see if this project could be used / ported for this usecase?

**Comment by mgnsk** [comment]
If your data is line-based and from streaming input, you could use `bufio.Scanner` to split it up first and then parse each line separately:
```go
func main() {
	scanner := bufio.NewScanner(os.Stdin)
	p := parser.NewParser()

	for scanner.Scan() {
		line, err := p.Parse(lexer.NewLexer(scanner.Bytes()))
		if err != nil {
			log.Fatal(err)
		}

		// Do something with the parsed log line.
		_ = line
	}

	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by gprossliner** [comment]
Thanks for your comment! This is exactly how I solved this issue back then.
