### ISSUE TITLE
wrong header in parser/productionstable.go?

### ISSUE THREAD

**Issue by hosewiejacke** [goccmack/gocc#17]
UPDATE: while reading the user guide for the 2nd time I saw this:

> An optional file header section, which is textually included in the generated parser file,
> parser/productionstable.go.

Which means the import paths in `parser/productionstable.go` are taken from the BNF file and aren't autogenerated. This solves the problem.

ORIGINAL:

I think `parser/productionstable.go` gets a wrong import path for *token* and *util* packages.

#### Steps to reproduce:

    $ go get github.com/goccmack/gocc
    $ cp -R $GOPATH/src/github.com/goccmack/gocc/example/calc /tmp/
    $ rm -rf $GOPATH/src/github.com/goccmack/gocc/example/calc
    $ cd /tmp/calc/
    $ gocc -p ".." calc.bnf

    $ cat > main.go
    
    package main
    
    import (
            "./lexer"
            "./parser"
    )
    
    func main() {
            _ = parser.NewParser()
            _ = lexer.NewLexer([]byte("1 + 1"))
    }
    ^D
    
#### Error when building

    $ go build main.go 
    parser/productionstable.go:7:2: open /tmp/calc/parser/token: no such file or directory
    parser/productionstable.go:8:2: open /tmp/calc/parser/util: no such file or directory

#### Temporary fix

    # parser/productionstable.go

    import(
        "../token"
        "../util"
    )

**Comment by awalterschulze** [comment]
Why did you close it?

**Comment by hosewiejacke** [comment]
Because the header of `parser/productionstable.go` is taken from the BNF.
Thus it's a feature not a bug ;)  I already updated the issue.

**Comment by awalterschulze** [comment]
Cool thanks :)
