### ISSUE TITLE
How can I specify a Unicode category in a lexer?

### ISSUE THREAD

**Issue by willfaught** [goccmack/gocc#22]
I'm experimenting with the [Haskell syntax](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html), which allows any uppercase (Lu) Unicode category character in certain places and not others. Is there a way to do that in gocc? Specifically, it uses the Unicode categories for whitespace, uppercase/titlecase and lowercase letters, symbols/punctuation, and decimal digits.

**Comment by awalterschulze** [comment]
I think you could probably build your own unicode categories in the lexer, but it is not provided out of the box by gocc.

**Comment by awalterschulze** [comment]
But it is a cool usecase.

**Comment by willfaught** [comment]
Yeah, I was hoping I wouldn't have to define the productions myself. I wish it was one easy char range, but no. ;)

**Comment by willfaught** [comment]
@awalterschulze Thanks!
