### ISSUE TITLE
Multi line SDT rules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [goccmack/gocc#3]
```
Feature Request for multi line SDT rules for example

<< func() { 
  return string($0.(*token.Token).Lit)
}, nil >>

Or

<< func() { 
  return string($0.(*token.Token).Lit) + "bla"
}, nil >>

Or

<< func() { 
  return string($0.(*token.Token).Lit) + `bla`
}, nil >>
```

Original issue reported on code.google.com by `awalterschulze` on 26 Apr 2013 at 1:52

**Comment by awalterschulze** [comment]
This is working, this case can be closed.

**Comment by mewmew** [comment]
Walter mentioned in https://github.com/goccmack/gocc/issues/3#issuecomment-114860303:
> This is working, this case can be closed.

As far as I can tell, support for multi line production actions has been implemented in Gocc for quite some time. Closing this issue to reflect the current status of Gocc.

**Comment by awalterschulze** [comment]
Perfect.
I forgot I had rights to do this now :)
