### ISSUE TITLE
Proposal: add travis job

### ISSUE THREAD

**Issue by awalterschulze** [goccmack/gocc#32]
I would like to replace drone with travis.
Since drone is not very well supported anymore.
What do you think? @goccmack @mewmew 

I would also like this travis job to then pull some other projects like gographviz for extra testing.
Maybe this is a little over zealous?

Also I would like to know how to regenerate all the current example grammars.
I can't seem to find a Makefile somewhere, am I missing something? @goccmack 
I think this should be part of testing gocc.
Otherwise what are we testing by running go test.

**Comment by goccmack** [comment]
I don't know travis. I will defer you a decision by @awalterschulze and @mewmew on this topic.
I am a bit uncomfortable about pulling external projects for testing gocc. That is serious coupling.
I usually write a makefile that generates the scanner & parser from the grammar for a project and I thought gocc's examples had those too. I only found a gen.sh in the bools example. The others either got lost or never existed. I also think it is a good idea to have a makefile to generate code for every grammar and invoke them from the top level. Are you volunteering @awalterschulze ?

**Comment by sangisos** [comment]
When fixing the line:col bug I recognized this while testing as all the examples where wrong. I was going to remove all the compiled and auto-generated parts from the examples, but it would include travis fixes. I didn't feel competent enough, even though I had seen @mewmew earlier implement travis with auto-generated gocc for https://github.com/mewmew/uc.

**Comment by awalterschulze** [comment]
Ok so this adds the regeneration in Makefiles
https://github.com/goccmack/gocc/pull/33

**Comment by awalterschulze** [comment]
I agree a gocc -clean flag would be really cool, maybe make that a separate issue.

**Comment by awalterschulze** [comment]
No problem @sangisos I am just glad that the line:col fix was done.  This was a HUGE step.

**Comment by awalterschulze** [comment]
Well basically the current gocc build using drone.io is broken.  It hasn't updated go in forever.
Travis integrates into github in such a way that you see that a pull request is built and you can see if it passes before you merge.
Also you can test against multiple go versions, or any single one you choose.
I also use it on gogoprotobuf to cross version test between go and protoc versions.

It is hard to report issues for travis, but I don't know of anything better at the moment.

If you want to add travis rather than drone you need to add an account at https://travis-ci.org/ and then I will volunteer to work on the .travis.yml file once you have do so.

**Comment by awalterschulze** [comment]
@goccmack Fair enough about the coupling.  This was also scaring me.
Maybe one big project like gographviz isn't tight coupling, since I am also in control over there.
Just seems like we don't have very big tests in this project.

**Comment by mewmew** [comment]
@awalterschulze Thanks for working on this and also to clean up the example and test regeneration.

I am in favour of switching to Travis CI if Drone is not well maintained. For an example .travis.yml config, you may refer to https://github.com/mewmew/uc/blob/master/.travis.yml

In the process, it would be wonderful to setup code coverage tracking through coveralls.io or similar services.

I wrote a small howto for setting these things up, https://github.com/decomp/decomp/issues/4#issuecomment-62314749

I would have to agree with @goccmack that I am not in favour of coupling gocc with any external dependencies unless this becomes a reoccurring problem where Gocc goes out of sync with projects. Even then, I think this issue should be solved through better practices regarding stable version handling and internal test cases of Gocc.

**Comment by awalterschulze** [comment]
I think as first step we can do something much simpler and closer to the current drone as a start.
Just a regenerate, git diff exitcode and go test.
Just so that we can get builds green again.

Although I am not a big fan of code coverage I don't have a problem with it, but maybe this can also be added in a separate step.

Ok I am very happy to leave out any tests of bigger usecases like gographviz.  I also agree it creates a tight coupling that I also don't like.   We simply can report issues here when we get them in our usecases.

**Comment by mewmew** [comment]
> I think as first step we can do something much simpler and closer to the current drone as a start.

Sounds good. Lets get the builder's green for starters. Then we can slowly extend these tests if so desired.

> Although I am not a big fan of code coverage I don't have a problem with it, but maybe this can also be added in a separate step.

That's ok. Code coverage may be used in the wrong way, just like anything. (E.g. check every line in Python code instead of static semantic analysis of types.)

>  We simply can report issues here when we get them in our usecases.

Sounds good.

**Comment by awalterschulze** [comment]
https://github.com/goccmack/gocc/pull/38

**Comment by awalterschulze** [comment]
Travis has been merged. If you want to add coveralls and/or errcheck, etc. I think it will be much easier now. But I think that can be done in a separate issue or simply a pull request. I am for errcheck and vet

**Comment by mewmew** [comment]
> Travis has been merged. If you want to add coveralls and/or errcheck, etc. I think it will be much easier now. But I think that can be done in a separate issue or simply a pull request. I am for errcheck and vet

Perfect!

We could also look into using the [gometalinter](https://github.com/alecthomas/gometalinter) which runs a series of static analysis tools to validate the source code. I agree, these may be added by future PRs.

**Comment by awalterschulze** [comment]
I think that will be an interesting experiment and probably even useful.
I also think that every new check will require some fixes.
So maybe starting like this
```
gometalinter --disable-all --enable=errcheck --enable=vet
```
And then slowly extending to some practical amount of checking would be very interesting.
