### ISSUE TITLE
Verbose output lacking error details

### ISSUE THREAD

**Issue by IzakMarais** [goccmack/gocc#47]
Running the example from _Chapter 10: Example: reduce/reduce conflict handling_ from the documentation gives:

```bash
> cd $GOPATH/src/github.com/goccmack/gocc/example/rr
> gocc -v rr.bnf
-a             = false
-debug_lexer   = false
-debug_parser  = false
-h             = false
-no_lexer      = false
-o             = T:\Documents\werk\badger\tools\src\github.com\goccmack\gocc\example\rr
-p             = github.com/goccmack/gocc/example/rr
-u             = false
-v             = true
-zip          = false
Error: 1 LR-1 conflicts
```

According to the documentation it should give:
```
> gocc -v rr.bnf
LR(1) conflict: S4 Reduce:3(B) / Reduce:4(A)
ABORTING: 1 LR(1) conflicts
```

This seems like a regression, since the cause of the conflict is no longer clearly explained.

**Comment by IzakMarais** [comment]
Browsing around in the folder reveals that this is likely just out of date docs. A `LR1_conflicts.txt` file is generated that contains the info required.

**Comment by IzakMarais** [comment]
I'll submit a pull request to update the documentation.

**Comment by awalterschulze** [comment]
Pull Requests are more than welcome :)

**Comment by IzakMarais** [comment]
Created https://github.com/goccmack/gocc/pull/48

**Comment by awalterschulze** [comment]
You fixed it :)
