### ISSUE TITLE
Providing context to parsers?

### ISSUE THREAD

**Issue by johnwchadwick** [goccmack/gocc#55]
I'm trying to parse a subset (not strict subset) of the C language using gocc. One of the challenges of this is that for C, the lexer needs to be fed by the parser continuously to know which identifiers should be treated as types, e.g. after a typedef. As far as I know, it's actually impossible to reasonably parse C without this knowledge (or maybe you could mangle your parser enough to handle it later in the AST, but I don't want to know how complicated that'd be. You'd end up doing the job of the parser basically anywhere things go ambiguous.)

Right now my plan is to try to wrap the gocc-generated scanner with something that changes idents to types as necessary. However, it still needs to read and interpret each declaration as it is reduced by the parser, and that's where things get a bit fuzzy.

So far, it seems the reducer functions do not have any access to the parser or additional context, so getting to the lexer would be an impossible task. This would be an incredibly useful addition to gocc, and as far as I can tell it would be doable without an API break. Should it be done?

There's a few options I can see.

1. Modify gocc to add an `interface{}` context object that can be set with a new setter. Feed this to the reducer functions, and it can be used as an escape hatch. Ugly, but very general. I don't think it requires any kind of API break.
2. Modify gocc to feed the scanner to the reducer functions. I'd argue this is still kind of ugly and much less general, but it does solve this specific problem. You'd still need to do some interface casting inside the reducer to get anywhere.
3. Super ugly solution: maintain a mapping of token.Token pointers to your context object, a bit like gorilla/context. I haven't tried it, but this probably works and probably solves the problem without modifying gocc at all. Yet again, it can be done without a custom lexer by wrapping the scanner. I'm probably going to do this for now to see if I can at least get things working for now.
4. Worst possible solution: global state. I can't use this in my case because I must recursively parse multiple translation units _without_ polluting the parent parser's/lexer's state (unlike, say, C includes, where that'd be fine.) Obviously, it's also not reentrant.

Any thoughts on this one? Seems challenging at least on the surface. Maybe I missed a much simpler option?

**Comment by mewmew** [comment]
Have you checked out https://en.wikipedia.org/wiki/The_lexer_hack? It discusses the very issue of typedefs in C. One way to handle this is to treat types as identifiers during lexing. This was the route taken by the [uC](https://github.com/mewmew/uc) compiler, which uses Gocc to produce lexers and parses for a subset of C. The uC compiler translates the C subset to LLVM IR, for later compilation using the LLVM toolchain.

**Comment by johnwchadwick** [comment]
I wasn't aware that it was such a well known problem at all and hadn't seen that. But now that I have, it's definitely interesting. Like I said, I imagined that would've been annoying because you have to do more work later on, but Clang does it, so it'd be hard to argue it's not a good solution.

Going to take a look at the uC compiler, thanks.

**Comment by mewmew** [comment]
> I wasn't aware that it was such a well known problem at all and hadn't seen that. But now that I have, it's definitely interesting. Like I said, I imagined that would've been annoying because you have to do more work later on, but Clang does it, so it'd be hard to argue it's not a good solution.

Me neither, before trying to write a grammar for C :)

> Going to take a look at the uC compiler, thanks.

You're welcome! If anything looks strange or you have some questions, feel free to reach out to me or @sangisos :)

Closing this issue for now, as Clang's solution seems to be an accepted way to keep the lexer context-free. If you still feel you would like to discuss a means of providing context from the lexer to the parser, feel free to re-open this issue.

Cheers /u
