### ISSUE TITLE
Have issue with space

### ISSUE THREAD

**Issue by lixingwang** [goccmack/gocc#56]
I define a bnf with lexer:
`!whitespace : ' ' | '\t' | '\n' | '\r';`
and grammar:
`Func1
	: function_name "(" Args ")"   << direction.NewFunction($0, $2) >>`

I expected that the grammar will ignore space and newline.... 
Then I tried with follow test cases:
1. concat("hello"," world")  -> working
2. concat(\n"hello"," world"\n)  -> working, change `\n `to` \t \r `are all working.
3. concat( "hello"," world") -> Not working.  Add space after ( or before ) both are not working.

Any suggestion? the only space `' '` not working others `\n \t \r`are working good.

I change lexer and grammer to:
`!whitespace : ' ' | '\t' | '\n' | '\r';
_empty : ' ';

space : {_empty} ;`

`	| function_name "(" space Args space ")"   << direction.NewFunction($0, $3) >>
`

Same result. not working either.

Please help me to figure out what's going wrong?

**Comment by mewmew** [comment]
Do you mind posting the full grammar? Potentially, the issue may be with quoted strings.

**Comment by awalterschulze** [comment]
Yes I suspect you only have problems with quoted strings since they are
defined in the lexer.

As I understand ignoring in gocc. It is that it ignores whitespace in
between tokens. But a quote starts recognizing the string token, so it
can't ignore it.

**Comment by lixingwang** [comment]
@mewmew @awalterschulze thanks. Posting part of my grammar which should explain the issue
```
/Space
_whitespace : ' ' | '\t' | '\n' | '\r' ;

space : {_whitespace} ;


//Double quotes strings
doublequotes_string : '"' {.} '"';
singlequote_string : '\'' {.} '\'' ;

wi_argument : '$' {_wistring} ;



Func :
    Func1
    | Expr
    ;
Func1
	: function_name "(" Args ")"   << direction.NewFunction($0, $2) >>
	| function_name "()"   << direction.NewFunction($0, "") >>
	| function_name "(" space Args space ")"   << direction.NewFunction($0, $3) >>
```

I suspend the white space with quotes string issue.  I change the function grammar to `function_name "(" space Args space ")"   << direction.NewFunction($0, $3) >>` but it still not working. 
manually add space in grammar that working but I don't want to limit it `function_name "(" "" space Args space "" ")"`

Is there a solution or a workaround for my case ?  I want to support multiple spaces after ( and before )? thanks so much.

**Comment by mewmew** [comment]
The following grammar is capable of parsing example 1 through 3,

```bnf
!_whitespace : ' ' | '\t' | '\n' | '\r' ;

doublequotes_string : '"' {.} '"';
singlequote_string : '\'' {.} '\'' ;

wi_argument : '$' {_wistring} ;

_ascii_letter
	: 'A' - 'Z'
	| 'a' - 'z'
;

_wistring : { _ascii_letter } ;

function_name : { _ascii_letter };

Func
	: Func1
	| Expr
;

Func1
	: function_name "(" Args ")"
	| function_name "()"
;

Expr
	: doublequotes_string
	| singlequote_string
	| wi_argument
;

Args
	: empty
	| ArgList
;

ArgList
	: Arg
	| Arg "," ArgList
;

Arg
	: Expr
;
```

Note the use of `!_whitespace` rather `space`, as `!token_name` roughly translates to *tokenize the input and then remove any token_name tokens from the stream of tokens*. Compared to the explicit use of `space` in `function_name "(" "" space Args space "" ")"`, this would not allow spaces in between arguments, as then Args would also need to contain explicit `space` tokens in the comma-separated list of arguments. The way to go is definitely to use `!token_name`.

Hope this helps.

**Comment by mewmew** [comment]
Note the grammar above makes a few assumptions regarding the definition of `Args`, `_wistring` and `function_name` as those were not included of the grammar you posted.

**Comment by awalterschulze** [comment]
I don't think you need empty here

```
Args
	: empty
	| ArgList
;
```

Or you don't need the empty option here:

```
Func1
	: function_name "(" Args ")"
	| function_name "()"
;
```

**Comment by mewmew** [comment]
You are indeed right.

**Comment by lixingwang** [comment]
Thanks, @mewmew I got it working by remove `space` and put `!_whitespace : ' ' | '\t' | '\n' | '\r' ;
` to the first line of the BNF file.

 but it is still weird that it would not work after putting `!_whitespace : ' ' | '\t' | '\n' | '\r' ;
` to the middle of the BNF file, not sure why and what is the difference?

Anyway now it resolved my issue by putting`!_whitespace : ' ' | '\t' | '\n' | '\r' ;
` to top line.  

Thanks for helping @mewmew @awalterschulze

**Comment by mewmew** [comment]
> but it is still weird that it would not work after putting !_whitespace : ' ' | '\t' | '\n' | '\r' ; to the middle of the BNF file, not sure why and what is the difference?

Lexer rules come first, then syntax rules. At least this is my understanding of Gocc. So you need to put all lexer rules before the first syntax rule.
