### ISSUE TITLE
litconv.go doesn't have utility method for handling float connversion

### ISSUE THREAD

**Issue by continuum-dipanjan-mazumder** [goccmack/gocc#57]
I cannot see any similar method which gets generated for handling float64 conversion in the util/litconv.g , while there are methods available for IntValue.

Please kindly let me know what do i have to do specifically to generate conversion handler method for Float similar to int64. 

This is an urgent usecase for my project and i am using inconventional way to explicitly implement a conversion method for float literal , which gets discarded as soon as i rebuild the grammar with gocc.

**Comment by awalterschulze** [comment]
I simply pass the float lit to my SDT function and parse it in there.

Here I define my float_lit
https://github.com/katydid/katydid/blob/master/relapse/bnf/all.bnf#L52

Here I use it
https://github.com/katydid/katydid/blob/master/relapse/bnf/all.bnf#L461

And here I parse it in my ast
https://github.com/katydid/katydid/blob/3cc919360f88cfb9a835a7b1b184f56dab30bdd3/relapse/ast/util.go#L140-L151

I hope this helps?

**Comment by continuum-dipanjan-mazumder** [comment]
Hi Walter,

This was absolutely helpful and thanks a ton for the prompt reply....

Regards
Dipanjan

**Comment by awalterschulze** [comment]
My pleasure.  Good luck.  I am closing the issue, but if you need more help we can just open it again.

**Comment by continuum-dipanjan-mazumder** [comment]
Sure thanks....
