### ISSUE TITLE
Defining a token for types in go

### ISSUE THREAD

**Issue by shivansh** [goccmack/gocc#59]
The following is a _minimal_ token identifier for [types in go](https://golang.org/ref/spec#Types) -
```
_unicode_letter : 'a' - 'z' | 'A' - 'Z' ;
_letter : _unicode_letter | '_' ;
identifier : _letter { _letter | _unicode_digit } ;
type : identifier |  '(' identifier ')' ;
```
The problem is that `identifier` needs to be a **token identifier**, although for `type` to work it should be defined as a **regular definition identifier**.
I guess a (bad?) workaround can be to define a duplicate **regular definition identifier** and then use it within `type` -
```
_identifier : _letter { _letter | _unicode_digit } ;
type : _identifier |  '(' _identifier ')' ;
```
Is there a better way for achieving the same ?

**Comment by awalterschulze** [comment]
This is exactly what I used to do, but then the lexer has trouble in guessing which token to return.  Is the token of type `identifier` or `type`.  Its not really possible to say, because its ambiguous.
To avoid this ambiguity I push this to the parser.

 ```
_unicode_letter : 'a' - 'z' | 'A' - 'Z' ;
_letter : _unicode_letter | '_' ;
identifier : _letter { _letter | _unicode_digit } ;

Type : identifier |  "(" identifier ")" ;
```

**Comment by shivansh** [comment]
Thanks!
