### ISSUE TITLE
header for generated files indicating that they are generated.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [goccmack/gocc#6]
```
It would be nice if all the generated files have the following header:

// Code generated by gocc.
// source: path/to/my.bnf
// DO NOT EDIT!

```

Original issue reported on code.google.com by `awalterschulze` on 9 Oct 2014 at 12:38

**Comment by awalterschulze** [comment]
The comments still require some work and is not complete.
Could you please reopen the issue.

**Comment by goccmack** [comment]
awalterschulze pointed out that:

The comments still require some work and is not complete.

**Comment by awalterschulze** [comment]
Thank you :)

**Comment by awalterschulze** [comment]
Would it be ok to change the internal API to accommodate these changes?

**Comment by mewmew** [comment]
Discussions related to this issue took place in pull request #12. Including some of the relevant ones for future reference.

Walter https://github.com/goccmack/gocc/pull/12#discussion_r52017893:
> Could we make it something closer to this
```go
// Code generated by protoc-gen-gogo.
// source: location/of/the/bnf/file.bnf
// DO NOT EDIT!
```

Robin https://github.com/goccmack/gocc/pull/12#discussion_r52065639:
> My friend and I were discussing this, and while the output would be a huge win, it may be difficult to get the BNF source name through to the code generation parts without changing the API of Gocc too much. Still, it is internal API as far as I'm aware, so this may still be a wise decision.

Walter https://github.com/goccmack/gocc/pull/12#discussion_r52118928:
> I think since its an internal API no one should really care if it changes.
> But I guess @goccmack should give his opinion.

Marius https://github.com/goccmack/gocc/pull/12#discussion_r52136769:
> I agree.

**Comment by cornelk** [comment]
@awalterschulze this is done

**Comment by mewmew** [comment]
> @awalterschulze this is done

Thanks @cornelk, closing this issue.
