### ISSUE TITLE
Supress generation of `LR1_conflicts.txt` and `LR1_sets.txt`

### ISSUE THREAD

**Issue by shivansh** [goccmack/gocc#61]
Is there currently a direct way to suppress generation of these files? When the number of LR-1 conflicts increase, the amount of time spent in I/O seems to be quite significant for a large BNF.

**Comment by awalterschulze** [comment]
Maybe you this:

```go
        switch {
	case !cfg.AutoResolveLRConf():
		fmt.Printf("Error: %d LR-1 conflicts\n", len(conflicts))
		io.WriteFileString(path.Join(cfg.OutDir(), "LR1_conflicts.txt"), conflictString(conflicts, numSets, prods))
		os.Exit(1)
	case cfg.Verbose():
		fmt.Printf("%d LR-1 conflicts \n", len(conflicts))
		io.WriteFileString(path.Join(cfg.OutDir(), "LR1_conflicts.txt"), conflictString(conflicts, numSets, prods))
	}
```

Should rather be:
```go
        if cfg.Verbose() {
             fmt.Printf("%d LR-1 conflicts \n", len(conflicts))
             io.WriteFileString(path.Join(cfg.OutDir(), "LR1_conflicts.txt"), conflictString(conflicts, numSets, prods))
        }
        if !cfg.AutoResolveLRConf() {
              os.Exit(1)
        }
```

https://github.com/goccmack/gocc/blob/master/main.go#L144-L152

@mewmew  what do you think?

**Comment by mewmew** [comment]
I think that the number of LR-1 conflicts should be displayed, even if `-v` is not provided, something along the lines of:

```go
if cfg.Verbose() {
	fmt.Printf("%d LR-1 conflicts\n", len(conflicts))
	io.WriteFileString(path.Join(cfg.OutDir(), "LR1_conflicts.txt"), conflictString(conflicts, numSets, prods))
}
if !cfg.AutoResolveLRConf() {
	fmt.Printf("Error: %d LR-1 conflicts\n", len(conflicts))
	os.Exit(1)
}
```

This way, an error is presented to the user, but no file is written to disk unless `-v` is provided.

**Comment by mewmew** [comment]
@shivansh Out of curiosity, what grammar are you working on?

**Comment by shivansh** [comment]
@mewmew It is go's [grammar](https://golang.org/ref/spec) ; we're writing a go to mips compiler, and the [bnf file](https://github.com/shivansh/gogo/blob/master/src/lang.bnf) is quite big (you should be able to access the repo now).

**Comment by mewmew** [comment]
Wow! That's really cool! Curiosity point nr 2, why keep it private?

**Comment by mewmew** [comment]
Oh, I see. It's course work.

**Comment by awalterschulze** [comment]
Ah ok good point

What about

```go
        fmt.Printf("%d LR-1 conflicts \n", len(conflicts))
        if cfg.Verbose() {
             io.WriteFileString(path.Join(cfg.OutDir(), "LR1_conflicts.txt"), conflictString(conflicts, numSets, prods))
        }
        if !cfg.AutoResolveLRConf() {
              os.Exit(1)
        }
```

**Comment by awalterschulze** [comment]
Or do you think the `Error:` string is important?

**Comment by awalterschulze** [comment]
@shivansh do you feel confident enough to make a pull request to fix this?

**Comment by awalterschulze** [comment]
It sounds like me and @mewmew are agreeing about 99%.  So go ahead an make a pull request that works the best for you.  Then we can review it :)

**Comment by mewmew** [comment]
> Or do you think the Error: string is important?

No, we can skip the `Error:` string and go with your suggestion. I just wanted to have some output before the time-consuming call to `conflictString`.

**Comment by mewmew** [comment]
@shivansh Thanks for the PR. It's now been merged. Keep us updated on your project :) It seems very interesting!
