### ISSUE TITLE
Replacing bytes.Buffer with strings.Builder?

### ISSUE THREAD

**Issue by kortschak** [goccmack/gocc#81]
In Go1.10, a string builder type, `strings.Builder` was added that reduces the number of allocations from the old approach of using `bytes.Buffer`. There are 58  instances in `gocc` where a bytes.Buffer is used in that way (another 11 are used for the bytes). It may be worth changing these.

The decision as to whether this should be done depends on the supported Go versions policy of gocc. At the moment the .travis.yml tests against 1.8.7, 1.94, 1.10,0 (these should probably be updated to .x and to include 1.11.x). If the policy is to retain those old versions, then the change cannot happen, but otherwise it could happen when say 1.12 is released.

**Comment by awalterschulze** [comment]
This is just a code generator and not a library, so I don't think we are too worried about supporting too many go versions.  If people aren't ready to update then they don't have to.

If you have time to change this, please also add some code generation times to the pull request.  It would be very helpful to see the speed improvement.  Increasing code generation speed is something that helps everyone.
