### ISSUE TITLE
Retain token.Location when generating AST

### ISSUE THREAD

**Issue by lmb** [goccmack/gocc#9]
Hello,

Is it possible to retain location information when building an AST? I'd like to generate error messages pointing at the offending line if a valid AST has logical inconsistencies.

Thanks

**Comment by awalterschulze** [comment]
Well you are the token.Token object when you are building your ast, which contains the position.

```
type Token struct {
	Type
	Lit []byte
	Pos
}

type Pos struct {
	Offset int
	Line   int
	Column int
}
```

**Comment by mewmew** [comment]
Marking this as resolved. In the future we may want to add an example which tracks AST node positions, and potentially a minimal semantic analysis package which showcases how to report errors with positional information.

Partly related to pull request #18 which gives users access to positional information contained within Gocc parse errors. These may be used for custom error handling during the syntactic analysis phase. For generating errors with positional information during the semantic analysis phase, users of Gocc should make sure to store the positional local of the relevant tokens at the corresponding nodes of the generated AST.

Also partly related to #19, which deals with tracking down the inaccurate reporting of line:col positions.

Closing this issue for now. @lmb, if you are still wondering something related to the issue, just give us a shout.
