### ISSUE TITLE
What is a difference [BNF]

### ISSUE THREAD

**Issue by Serhioromano** [goccmack/gocc#98]
In one of the example i so something like this

```
Statement : "if" something "then" ;
```

What is a difference? Why we do 

```
if: 'i' 'f' ;
```

If we can use it like `"if"`?

I have a lot of keywords that is gonna be used only once in fact. For instance here is a program

```iecst
PROGRAM
    VAR
        xStart: BOOL;
    END_VAR
    xStart := TRUE;
END_PROGRAM
```

can i make BNF like this

```bnf
Programs :
    Program
    | Programs Program
    ;

Program : "PROGRAM" Vars Statements "END_PROGRAM"
```

Or I have to define?

```
prog : 'P' 'R' 'O' 'G' 'R' 'A' 'M' ;
```

**Comment by awalterschulze** [comment]
This is a great question.
I remember I have sometimes needed to switch between the two modes, but can't remember why.

@AntonHendriks  @goccmack

**Comment by goccmack** [comment]
The string version "if" is a shortcut in the syntax part of the grammar that spares you the trouble of having to define a token, if : 'i' 'f' ; in the lexical part.
Both forms produce an equivalent token in the lexer, except that in the case of the string literal the token does not have an ID defined by the grammar writer.

I normally use the string version for all reserved words of the language.
